### ISSUE TITLE
Use multiple topics

### ISSUE THREAD

**Issue by mroda88** [DUNE-DAQ/erskafka#5]
At present only one topic is used to export the ERS messages, namely `erskafka-reporting`. 
We might want to have more separation in order to be more efficient in organising the informations.

**Comment by bieryAtFnal** [comment]
I talked with Marco about this Issue, and my understanding is that it should be deferred until after v2.11.0.  So, I am updating its Target Release field to have v3.0.0.  Marco mentioned that he hasn't had success in monitoring the kafka server effectively, so any changes to the topics wouldn't be useful at this point in time.
One question that came up was whether there has been any success in sending the opmon metrics through the Kafka broker.  I didn't know the answer to that...

**Comment by tapperad** [comment]
Marco is still working on monitoring the kafka server which is close but not there yet. 

Likewise using multiple topics is in scope for v.3 but not quite there yet.

Opmon - Kafka has not been investigated further. The package exists from Yann but not looked at again. Likely for v3.1.0

**Comment by mroda88** [comment]
ERS is the the stream with the lowest consumption of the kafka resources, compared to DQM and opmon. So it seems there is no need for using multiple topics in kafka. It's more likely that the issue might arise for the opmon stream.
